# -*- coding: utf-8 -*-
# Generated By QuMod McEventCodeGen.py

class AttackAnimBeginClientEvent(object):
    """ 攻击动作开始时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

class AttackAnimBeginServerEvent(object):
    """ 当攻击动作开始时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

class AttackAnimEndClientEvent(object):
    """ 攻击动作结束时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

class AttackAnimEndServerEvent(object):
    """ 当攻击动作结束时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

class JumpAnimBeginServerEvent(object):
    """ 当跳跃动作开始时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

class WalkAnimBeginClientEvent(object):
    """ 走路动作开始时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

class WalkAnimBeginServerEvent(object):
    """ 当走路动作开始时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

class WalkAnimEndClientEvent(object):
    """ 走路动作结束时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

class WalkAnimEndServerEvent(object):
    """ 当走路动作结束时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")
